version: "3.7"

services:

  dev:
    build: .
    volumes:
      - ./pyproject.toml:/home/python/app/pyproject.toml
      - ./poetry.lock:/home/python/app/poetry.lock
      - ./.flake8:/home/python/app/.flake8
      - ./visiont:/home/python/app/visiont
